spring:
  application:
    name: itau
  datasource:
    url: jdbc:postgresql://db:5432/itau
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
server:
  port: 8080